# Generated by Django 5.0.6 on 2024-05-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_venta_fecha_venta_venta_total_detalle_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
