# Generated by Django 5.0.3 on 2024-04-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rut',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
